### PR TITLE
Update dependencies instructions

### PR DESCRIPTION
**Pull request by felipe-lee**
1. Update `aws-vault` install command since it has changed.

I'm not sure who exactly I should ask for reviews from so I just went with github's suggestion.

### CODE REVIEW

**Review by dynamike — COMMENTED** [review]
The setup-new-aws-user script does not explicitly need direnv. That's more project specific, which I think would be in the milmove docs.

**Comment by felipe-lee** [comment]
Ah ok. In that case, I'll only leave the change to the installation for `aws-vault`

**Review by dynamike — APPROVED** [review]

**Comment by eeeady** [comment]
Thank you for updating!!!

**Comment by felipe-lee** [comment]
Glad to help 😄

**Pull request merged**
